---
title: DINSIC
timezone: Europe/Paris
collections:
  actualites:
    title: Actualités
    output: true
  communiques:
    title: Communiqués
    output: true
    Data:
      address_ref:
  evenements:
    title: Evènements
    output: true
  posts:
    title: Posts
    output: true
  actualites:
    title: Actualités
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: actualites
  values:
    layout: post
    permalink: "/actualites/:title/"
- scope:
    path: ''
    type: communiques
  values:
    communique_file: "/uploads/exemple.pdf"
    layout: communique
    permalink: "/espace-presse/:title/"
- scope:
    path: ''
    type: evenements
  values:
    layout: post
    permalink: "/evenements/:title/"
url: dinsic.gouv.fr
contact-presse:
  name: Rachel Wadoux
  tel:
  - 01.71.21.11.98
  - 06.34.21.55.48
  email: rachel.wadoux@modernisation.gouv.fr
categories:
- main
language: fr
markdown: kramdown
description: Le site officiel de la DINSIC
include:
- ".htaccess"
- _pages
exclude:
- ".DS_Store"
- ".circleci/"
- bower.json
- composer.json
- composer.lock
- DOC.md
- "/gulp/"
- gulpfile.js
- LICENSE.md
- Makefile
- node_modules
- npm-debug.log
- package.json
- README.md
- rev-manifest.json
- yarn.lock
- yarn-error.log
- "/ansible/"
- "/node_modules/"
pagination:
  enabled: true
  per_page: 2
  permalink: "/page/:num/"
  title: ":title - page :num de :max"
  limit: 0
  sort_field: date
  sort_reverse: true
incremental: true
compress_html:
  ignore:
    envs:
    - development
highlighter: rouge
