---
title: DINSIC
timezone: UTC
collections:
  actualites:
    title: Actualites
    output: true
    permalink: "/actualites/:path/"
  posts:
    title: Posts
    output: true
  presse:
    title: Presse
    output: true
    permalink: "/espace-presse/:path/"
  uploads:
    title: Uploads
    output: true
description: Le site officiel de la DINSIC
language: Fr
plugins:
- jekyll-paginate-v2
include:
- ".htaccess"
- _pages
exclude:
- ".DS_Store"
- "/assets/"
- bower.json
- composer.json
- composer.lock
- DOC.md
- Gemfile
- Gemfile.lock
- "/gulp/"
- gulpfile.js
- LICENSE.md
- Makefile
- node_modules
- npm-debug.log
- package.json
- README.md
- rev-manifest.json
- yarn.lock
- yarn-error.log
- "/ansible/"
permalink: "/:year/:month/:title.html"
pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"
  title: ":title - page :num of :max"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: actualites
compress_html:
  ignore:
    envs:
    - development
highlighter: rouge
