---
title: DINSIC
timezone: UTC
collections:
  posts:
    title: Actualités
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/actualités/:title/"
language: Fr
markdown: kramdown
description: Le site officiel de la DINSIC
plugins:
- jekyll-paginate-v2
include:
- ".htaccess"
- _pages
exclude:
- ".DS_Store"
- bower.json
- "/assets/"
- composer.json
- composer.lock
- DOC.md
- Gemfile
- Gemfile.lock
- "/gulp/"
- gulpfile.js
- LICENSE.md
- Makefile
- node_modules
- npm-debug.log
- package.json
- README.md
- rev-manifest.json
- yarn.lock
- yarn-error.log
- "/ansible/"
- "/node_modules/"
permalink: "/:year/:month/:title.html"
pagination:
  enabled: true
  per_page: 2
  permalink: "/page/:num/"
  title: ":title - page :num of :max"
  limit: 0
  sort_field: date
  sort_reverse: true
incremental: true
compress_html:
  ignore:
    envs:
    - development
highlighter: rouge
