version: 2
jobs:
  build:
    working_directory: ~/dinsic
    docker:
      - image: starefossen/ruby-node:latest
        environment:
          - HOST: test-dinsic.fr
          - LOGIN: root
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v
      # Restore bundle cache
      - restore_cache:
          keys:
            - dinsic-v1-{{ checksum "Gemfile.lock" }}
            - dinsic-v1-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: dinsic-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Yarn build
          command: yarn build-dev

      - store_artifacts:
          path: ~/dinsic/_site
          destination: site-dinsic

  deploy:
    requires:
      - build
    working_directory: ~/dinsic
    docker:
      - image: instrumentisto/rsync-ssh:latest
        environment:
          - HOST: test-dinsic.fr
          - LOGIN: root
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "df:52:a0:dc:24:38:fc:80:38:71:f1:ef:6b:32:4d:d4"

      - deploy:
          name: Deploy on OVH
          command: rsync --compress --archive -e "/usr/share/centrifydc/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./_site $LOGIN@$HOST:/var/www/html/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy


