version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: docker pull starefossen/ruby-node
        environment:
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

