version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:latest
    steps:
      - restore_cache:
          name: Restore Git Cache
          keys:
            - source-v5-{{ .Branch }}-{{ .Revision }}
            - source-v5-{{ .Branch }}-
            - source-v5-

      - checkout

      - save_cache:
          name: Save Git Cache
          key: source-v5-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      # Restore bundle cache
      - restore_cache:
          name: Restore Gem Cache
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1

      - run:
          name: Bundle Install
          command: bundle check --path=/vendor/bundle || bundle install --path=/vendor/bundle --jobs=4 --retry=3

      # Store bundle cache
      - save_cache:
          name: Save Gem Cache
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - /vendor/bundle

      - run:
          name: change yarn cache config
          command: yarn config set cache-folder ~/.cache/yarn

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - restore_cache:
          name: Restore Node module cache
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save Node module cache
          paths:
            - /root/project/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn build
          command: yarn build-dev
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "siteleaf" ]; then
              yarn build
            else
              yarn build-dev
            fi

      - persist_to_workspace:
          root: /root/project
          paths:
            - _site/*

  test-html:
    docker:
      - image: python:3.6-stretch
    steps:
      - run:
          name: install Java
          command: apt-get update && apt-get install -y openjdk-8-jre
      - run:
          name: install
          command: pip install html5validator
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: validate html
          command: html5validator --root /tmp/workspace/_site/

  deploy:
    machine:
        enabled: true
    environment:
      - HOST: test-dinsic.fr
      - LOGIN: root
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - add_ssh_keys:
          fingerprints:
            - "31:8a:07:d1:56:88:18:c4:4e:91:5f:13:0c:58:b6:cc"
      - run:
          name: add key
          command: echo $REMOTE_DEV_HOSTKEY >> ~/.ssh/known_hosts

      - deploy:
          name: Deploy on OVH
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Not yet develop"
            elif [ "${CIRCLE_BRANCH}" == "development" ] || [ "${CIRCLE_BRANCH}" == "siteleaf" ]; then
              rsync -avc /tmp/workspace/_site/ $LOGIN@$HOST:/var/www/html/
            else
              echo "Not development branch, dry run only"
            fi


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test-html
          requires:
            - build
      - deploy:
          requires:
            - test-html
            - build



