version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:latest
    steps:
      - restore_cache:
          name: Restore Git Cache
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - save_cache:
          name: Save Git Cache
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      # Restore bundle cache
      - restore_cache:
          name: Restore Gem Cache
          keys:
            - dinsic-v3-{{ checksum "Gemfile" }}
            - dinsic-v3-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          name: Save Gem Cache
          key: dinsic-v3-{{ checksum "Gemfile" }}
          paths:
            - vendor/cache

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v3-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --cache-folder '/root/.cache/yarn'
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v3-{{ checksum "yarn.lock" }}
          paths:
            - /root/.cache/yarn

      - run:
          name: Yarn build
          command: yarn build-dev
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "siteleaf" ]; then
              yarn build
            else
              yarn build-dev
            fi

      - persist_to_workspace:
          root: /root/project
          paths:
            - _site/*


  deploy:
    machine:
        enabled: true
    environment:
      - HOST: test-dinsic.fr
      - LOGIN: root
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - add_ssh_keys:
          fingerprints:
            - "31:8a:07:d1:56:88:18:c4:4e:91:5f:13:0c:58:b6:cc"
      - run:
          name: add key
          command: echo $REMOTE_DEV_HOSTKEY >> ~/.ssh/known_hosts

      - deploy:
          name: Deploy on OVH
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Not yet develop"
            elif [ "${CIRCLE_BRANCH}" == "development" ] || [ "${CIRCLE_BRANCH}" == "siteleaf" ]; then
              rsync -avc /tmp/workspace/_site/ $LOGIN@$HOST:/var/www/html/
            else
              echo "Not development branch, dry run only"
            fi


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build



