version: 2
jobs:
  build:
    working_directory: ~/dinsic
    docker:
      - image: starefossen/ruby-node:latest
        environment:
          - HOST: test-dinsic.fr
          - LOGIN: root
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v
      # Restore bundle cache
      - restore_cache:
          keys:
            - dinsic-v1-{{ checksum "Gemfile.lock" }}
            - dinsic-v1-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: dinsic-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Yarn build
          command: yarn build-dev

      - store_artifacts:
          path: ~/dinsic/_site
          destination: site-dinsic

  deploy:
    machine:
        enabled: true
    working_directory: ~/dinsic
    environment:
      - HOST: test-dinsic.fr
      - LOGIN: root
      - BUILD_DIR: _site
    steps:
      - add_ssh_keys:
          fingerprints:
            - "31:8a:07:d1:56:88:18:c4:4e:91:5f:13:0c:58:b6:cc"
      - run: echo $REMOTE_DEV_HOSTKEY >> ~/.ssh/known_hosts

      - deploy:
          name: Deploy on OVH
          command: rsync -avc $BUILD_DIR root@test-dinsic.fr:/var/www/html/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy



