version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:latest
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Folder?
          command: pwd
      # Restore bundle cache
      - restore_cache:
          keys:
            - dinsic-v1-{{ checksum "Gemfile.lock" }}
            - dinsic-v1-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: dinsic-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Yarn build
          command: yarn build-dev

      - persist_to_workspace:
          root: /root/project
          paths:
            - _site/*



  deploy:
    machine:
        enabled: true
    environment:
      - HOST: test-dinsic.fr
      - LOGIN: root
    steps:
      - attach_workspace:
         at: /_site

      - add_ssh_keys:
          fingerprints:
            - "31:8a:07:d1:56:88:18:c4:4e:91:5f:13:0c:58:b6:cc"
      - run:
          name: add key
          command: echo $REMOTE_DEV_HOSTKEY >> ~/.ssh/known_hosts

      - deploy:
          name: Deploy on OVH
          command: rsync -avc ./_site root@test-dinsic.fr:/var/www/html/


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build



