version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: starefossen/ruby-node:latest
        environment:
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v
      # Restore bundle cache
      - restore_cache:
          keys:
            - dinsic-v1-{{ checksum "Gemfile.lock" }}
            - dinsic-v1-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: dinsic-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - dinsic-v1-{{ checksum "yarn.lock" }}
            - dinsic-v1-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: dinsic-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      -run:
        name: Yarn start
        name: yarn start


