htpasswd_credentials:
      - path: /etc/nginx/passwdfile
        name: dinsic
        password: 'supersecure'
        owner: root
        group: www-data
        mode: 'u+rw,g+r'

nginx_remove_default_vhost: True
nginx_vhosts:
  - listen: "80"
    server_name: "htpassword.test"
    root: "/var/www/html"
    index: "index.html index.html index.nginx-debian.html"
    filename: "htpassword.test.conf"
    extra_parameters: |
          location / {
              auth_basic           "Nginx with basic auth.";
              auth_basic_user_file /etc/nginx/passwdfile;
              }
