---
# Fetch latest release GeoIP database
- name: "Fetch latest GeoIP database"
  action: get_url url={{ matomo.geoip.url }}/{{ matomo.geoip.file }} dest={{ matomo.settings.locations.dest }}/misc/ mode=0660 owner={{ matomo.nginx.user }} group={{ matomo.nginx.group }}
  register: geoip_db

# Extract GeoIP database
- name: "Extract GeoIP database"
  action: shell gunzip -c {{ matomo.settings.locations.dest }}/misc/{{ matomo.geoip.file }} > {{ matomo.settings.locations.dest }}/misc/{{ matomo.geoip.dest }}
  when: geoip_db.changed
