---
- include: dependencies_deb.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: db.yml

# Fetch latest release
- name: "Fetch latest Piwik release"
  action: get_url url={{ matomo.settings.url }}/{{ matomo.settings.file }} dest={{ matomo.settings.locations.tmp }} mode=0440 owner=root group=root

# Create Piwik destination folder
- name: "Create Piwik destination folder"
  action: file path={{ matomo.settings.locations.install }} owner={{ matomo.nginx.user }} group={{ matomo.nginx.group }} mode=0755 state=directory

# Extract package
- name: "Extract Piwik zipfile"
  unarchive:
    creates: "{{ matomo.settings.locations.dest }}"
    owner: "{{ matomo.nginx.user }}"
    group: "{{ matomo.nginx.group }}"
    mode: 0755
    remote_src: yes
    src: "{{ matomo.settings.locations.tmp }}/{{ matomo.settings.file }}"
    dest: "{{ matomo.settings.locations.install }}"

# Create Piwik temp folders
- name: "Create Piwik temp folders"
  file: path={{ matomo.settings.locations.dest }}/{{ item }} owner={{ matomo.nginx.user }} group={{ matomo.nginx.group }} mode=0755 state=directory
  with_items: matomo.settings.web_writable_dirs


- name: "Start and enable Nginx"
  action: service name={{ matomo.nginx.service }} state=started enabled=yes

- include: geoip.yml
