---
- hosts: dev
  remote_user: root
  vars_files:
      - vars/main.yml
  pre_tasks:
    - name: Update apt cache.
        apt: update_cache=yes cache_valid_time=600
        when: ansible_os_family == 'Debian'
        changed_when: false

    - name: Install cron (Debian).
          apt: name=cron state=present
          when: ansible_os_family == 'Debian'

  roles:
    - common
    - ansible-role-nginx
    - ansible-role-htpasswd

